### ISSUE TITLE
Spec is confusing?

### ISSUE THREAD

**Issue by kengruven** [kstenerud/compact-float#2]
For some reason, I find this specification rather confusing.  (Is it just me?)  I think it's actually simpler than it looks.

There's only 6 "special values" that I see, with no real possibility to ever add any more, and they correspond to the fixed byte sequences [02], [03], [80 00], [81 00], [82 00], and [83 00].  I can't tell what the "Extended exponent" section is trying to say at all.  When would you ever need to write a [7c] (-> [fc 00]) byte?

I suppose it's true that nan = [80 00] is what you'd get if you wanted to encode byte [00] in LEB128 and somehow convinced your LEB128 encoder to use one extra byte than needed.  But no existing LEB128 function supports that, and it would serve no purpose anywhere else (even anywhere else in CBE, AFAICT), and it's just unnecessary complexity to suggest it here.

It might be simpler to say something like: "For these 6 special values, here are 6 special byte sequences you can hard-code.  Due to the way LEB128 (and the Exponent Structure) works, they are guaranteed to never collide with any actual exponent."

**Comment by kstenerud** [comment]
I've updated the spec to remove the emphasis on the mechanism for deriving these special values. Hopefully it's less confusing now!

**Comment by kengruven** [comment]
Thanks.  It makes more sense to me now.
